list = [1,3,4,'deepak']
print(list)
list2 = [3,4,5,'amit','renu']
print(list2)
print(list[3])
print(list2[2:5])
print(list[0:4])
list.append(66)
print(list)
list.extend([55,77])
print(list)
print(len(list))
list.insert(6, 'chauhan')
print(list)
print(list.index('deepak'))
print(list.index('chauhan'))
list.reverse()
print(list)
list3 = [1,2,3,4,5,6,7,8,9,0]
print(list3)
list3.sort()
print(list3)